### ISSUE TITLE
Rendering and Blender Scene Loading Issues - 'UnicodeDecodeError'

### ISSUE THREAD

**Issue by Masoudvahid** [Anttwo/sugar_frosting_blender_addon#1]
Hello,

First of all, I would like to express my appreciation for your amazing work on Gaussian Frosting. It’s an incredibly interesting plugin, and I’m excited to be using it! I am currently trying to recreate the results I previously trained using the SuGaR repository, but I’ve encountered two main issues:

1. When I press Render Image or Render Animation, nothing happens and I don't get any output. There are no error messages or logs indicating what went wrong.

2. I am saving my scene as a `.blend `file in the `<SuGaR>/blender/packages directory`. However, when I run:
3. 
```bash
python render_blender_scene.py -p <PATH_TO_PACKAGE>
``` 
I receive the following error:

```bash
Using original 3DGS rasterizer from Inria.
[INFO] Using device:  cuda:0
[INFO] Images will be saved in:  ./output/blender/renders/a2

Loading Blender package...
Traceback (most recent call last):
  File "/SuGaR/render_blender_scene.py", line 60, in <module>
    package = load_blender_package(args.package_path, device)
  File "/SuGaR/blender/sugar_utils.py", line 17, in load_blender_package
    package = json.load(open(package_path))
  File "/miniconda3/envs/sugar/lib/python3.9/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/miniconda3/envs/sugar/lib/python3.9/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf0 in position 20: invalid continuation byte
``` 

I have updated my old SuGaR repository and environment, and I am using Blender 4.0.2.

Any help or guidance would be greatly appreciated!

Thank you for your hard work and support!

**Comment by MichaelYu781** [comment]
i have met the save problem: nothing happens when i press render image or render animation

**Comment by nepfaff** [comment]
>When I press Render Image or Render Animation, nothing happens and I don't get any output. There are no error messages or logs indicating what went wrong.

I had the same issue and for me it turned out to be that I didn't save the Blender scene. It then tried to save a json file with no basename which didn't do anything

**Comment by DebbyX3** [comment]
Had a similar issue where I couldn't figure out where the .json was saved, since the Blender scripting windows wasn't throwing any errors or anything, but just this message: `bpy.ops.object.sugar_render_single()`

In Blender I set the "Path to Sugar/Frosting directory" pointing to the sugar root directory, e.g. `C:\Users\User\SuGaR`
After pressing 'render image' I expected the .json file to be saved in `C:\Users\User\SuGaR\blender\package\scene_name`, as the readme suggests

Only after using a debugger for Blender addons I discovered the actual position is a different one... 

It was saving into `C:\Users\User\SuGaR\output\blender\package`, notice the 'output' directory!

Please also remember to save the blender file otherwise the .json would have a blank name

(running on Windows btw)
